package com.example.ragdemo.model;

import java.util.List;

/**
 * Domain model representing one chunk stored in the vector database.
 *
 * @param chunkId     Unique chunk id.
 * @param documentId  Parent document id.
 * @param title       Parent document title.
 * @param source      Parent source identifier.
 * @param chunkIndex  Chunk order in original content.
 * @param text        Raw text content for this chunk.
 * @param embedding   Dense embedding vector generated by Ollama.
 */
public record VectorChunk(
        String chunkId,
        String documentId,
        String title,
        String source,
        int chunkIndex,
        String text,
        List<Double> embedding
) {
}
